---

- name: Install virtualenv
  pip: name=virtualenv version={{ virtualenv_version }}
  sudo: true
  tags:
    - python
    - virtualenv
    - install

- name: Create virtualenvs
  shell: if test -d {{ virtualenv_prefix }}/{{ item }}; then echo "false"; else  virtualenv {{ virtualenv_prefix }}/{{ item }}; fi
  register: virtualenv_out
  changed_when: "virtualenv_out.stdout.find('false') == -1"
  with_items: virtualenvs_to_create
  # this is needed to execute the command as different user
  sudo: true
  sudo_user: "{{ virtualenv_user }}"