---

- name: Create ssh and cloud instances
  hosts: 127.0.0.1 # this hasn't got a target host
  connection: local
  gather_facts: False

  vars_files:
    - roles/creation/vars/sshkeys.yml
    - roles/creation/vars/instances.yml

  roles:
    - creation
  tags:
    - creation
    - setup