---

- name: Install common dependencies
  hosts: all
  sudo: true
  roles:
    - common
  tags:
    - pre
    - common

- name: Install virtualenv
  hosts: webservers
  roles:
    - virtualenv
  tags:
    - virtualenv

- name: Install uwsgi
  hosts: webservers
  sudo: true
  roles:
    - uwsgi
  tags:
    - uwsgi